package raytracer.ui;

import javax.swing.JFrame;

import raytracer.Renderer;
import raytracer.image.TracerCanvas;

/**
 * Class to display images generated by a Raytracer.
 * 
 * <p>The class generates a window adapted to the size defined in 
 * the raytracer object.
 * 
 * @author Simon Lischka
 *
 */
public final class ShowImage {
	/**
	 * Calls Raytracers tracing method and displays the resulting ImageBuffer.
	 * 
	 * @param raytracer Raytracer to be displayed; must implement trace() function 
	 * @param x Horizontal coordinate of the window location
	 * @param y Vertical coordinate of the window location
	 */
	public static void from(final Renderer raytracer, final int x, final int y) {
		final TracerCanvas mainCanvas = new TracerCanvas(raytracer.render());
		final JFrame frame = new JFrame();
		frame.getContentPane().add(mainCanvas);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setSize(raytracer.getSize().width, raytracer.getSize().height);
		frame.setLocation(x, y);
		frame.setVisible(true);
	}
	
	/**
	 * Calls Raytracers tracing method and displays the resulting ImageBuffer.
	 * Displays the window in a default location on the top left corner of the
	 * screen.
	 * 
	 * @param raytracer Raytracer to be displayed; must implement trace() function 
	 */
	public static void from(final Renderer raytracer) {
		from(raytracer, 0, 0);
	}
}
